### PR TITLE
IndicatorList Add collapsed mode Issue 55

### PR DESCRIPTION
**Pull request by simbatsuro**

### CODE REVIEW

**Comment by moshloop** [comment]
In collapsed mode the collapse/expand icon is on the entire Indicator Panel and each IndicatorCard shrinks to a single 48x48 icon with overlays

**Comment by simbatsuro** [comment]
Perhaps a 38x38 icon in a 48x48 parent would be less bulky?

**Comment by moshloop** [comment]
Can we add them as badges? The separators and whitespace also need to come out it should just be the icons
Screenshot 2020-10-29 at 08 44 50

**Comment by moshloop** [comment]
Looking better, - the entire panel still doesn't resize down on collapse i.e. their is too much whitespace

**Comment by simbatsuro** [comment]
Are you referring to such a design?
indicatorspanel

**Comment by moshloop** [comment]
Yes, but if the left-side higher it should wrap.

**Comment by simbatsuro** [comment]
Like so?

**Comment by moshloop** [comment]
Yes

**Comment by moshloop** [comment]
Looking better - The badges should only display in collapsed mode though

**Comment by moshloop** [comment]
Please fix merge conflicts

**Pull request merged**
