### PR TITLE
feat: add collapsible left navbar

### LINKED ISSUE #71: LeftNavBar - Add collapsed option

### PR DESCRIPTION
**Pull request by simbatsuro**
Close #71

### CODE REVIEW

**Comment by moshloop** [comment]
So this isn't a popover, rather a full-height panel, that replaces the top menu completely  (There might be another menu in the right panel, but it should be under/over the left panel, when collapsed, the menu just has icons and no text

**Comment by moshloop** [comment]
This adds an additional sidebar rather than replacing the existing sidebar? It also isn't full height 

It also shouldn't have any hover effects - rather only a collapse/expand on clicking the main burger icon,

**Comment by simbatsuro** [comment]
Is this a little warmer?

**Comment by moshloop** [comment]
Its getting better - I think completely remove the header with "Karina - Kubernertes dashboard"

**Comment by moshloop** [comment]
@simbatsuro please rebase

**Comment by simbatsuro** [comment]
all done. appears good

**Pull request closed without merging**
